### ISSUE TITLE
What's Going on With RWIS?

### ISSUE THREAD

**Issue by Markweese** [BoulderCodeHub/usbrrwis#1]
I know this isn't the most conventional way to surface this, but I've had trouble finding any information about the issue I'm encountering: do you know why RWIS, and everything under the water.usbr.gov domain appears to be down? I've been trying to get water storage data from the service for the past few weeks and have had no luck. Any insight would be greatly appreciated!

**Comment by rabutler-usbr** [comment]
@Markweese - I'm not 100% sure as I am not all that involved in the project, but I believe everything has been transitioned to data.usbr.gov. 

If you don't see what you need there, let me know, or email data@usbr.gov.

**Comment by Markweese** [comment]
@rabutler-usbr Thank you, everything works as expected on data.usbr.gov.
